import json

# Liste des 195 États souverains (Nom officiel, alias, code ISO 2 lettres)
COUNTRIES_DATA = [
    # Afrique
    ("Afrique du Sud", ["South Africa"], "za"),
    ("Algérie", ["Algerie", "Algeria"], "dz"),
    ("Angola", [], "ao"),
    ("Bénin", ["Benin"], "bj"),
    ("Botswana", [], "bw"),
    ("Burkina Faso", [], "bf"),
    ("Burundi", [], "bi"),
    ("Cabo Verde", ["Cap-Vert", "Cap Vert"], "cv"),
    ("Cameroun", ["Cameroon"], "cm"),
    ("Comores", ["Comoros"], "km"),
    ("Congo-Brazzaville", ["Congo", "Republique du Congo"], "cg"),
    ("Congo-Kinshasa", ["RDC", "RDCongo", "Republique Démocratique du Congo"], "cd"),
    ("Côte d'Ivoire", ["Cote d'Ivoire", "Ivory Coast"], "ci"),
    ("Djibouti", [], "dj"),
    ("Égypte", ["Egypte", "Egypt"], "eg"),
    ("Érythrée", ["Erythree", "Eritrea"], "er"),
    ("Eswatini", ["Swaziland"], "sz"),
    ("Éthiopie", ["Ethiopie", "Ethiopia"], "et"),
    ("Gabon", [], "ga"),
    ("Gambie", ["Gambia"], "gm"),
    ("Ghana", [], "gh"),
    ("Guinée", ["Guinee", "Guinea"], "gn"),
    ("Guinée-Bissau", ["Guinee Bissau"], "gw"),
    ("Guinée équatoriale", ["Guinee equatoriale"], "gq"),
    ("Kenya", [], "ke"),
    ("Lesotho", [], "ls"),
    ("Libéria", ["Liberia"], "lr"),
    ("Libye", ["Libya"], "ly"),
    ("Madagascar", [], "mg"),
    ("Malawi", [], "mw"),
    ("Mali", [], "ml"),
    ("Maroc", ["Morocco"], "ma"),
    ("Maurice", ["Mauritius"], "mu"),
    ("Mauritanie", ["Mauritania"], "mr"),
    ("Mozambique", [], "mz"),
    ("Namibie", ["Namibia"], "na"),
    ("Niger", [], "ne"),
    ("Nigéria", ["Nigeria"], "ng"),
    ("Ouganda", ["Uganda"], "ug"),
    ("Rwanda", [], "rw"),
    ("Sao Tomé-et-Principe", ["Sao Tome"], "st"),
    ("Sénégal", ["Senegal"], "sn"),
    ("Seychelles", [], "sc"),
    ("Sierra Leone", [], "sl"),
    ("Somalie", ["Somalia"], "so"),
    ("Soudan", ["Sudan"], "sd"),
    ("Soudan du Sud", ["South Sudan"], "ss"),
    ("Tanzanie", ["Tanzania"], "tz"),
    ("Tchad", ["Chad"], "td"),
    ("Togo", [], "tg"),
    ("Tunisie", ["Tunisia"], "tn"),
    ("Zambie", ["Zambia"], "zm"),
    ("Zimbabwe", [], "zw"),

    # Amériques
    ("Antigua-et-Barbuda", ["Antigua"], "ag"),
    ("Argentine", ["Argentina"], "ar"),
    ("Bahamas", [], "bs"),
    ("Barbade", ["Barbados"], "bb"),
    ("Belize", [], "bz"),
    ("Bolivie", ["Bolivia"], "bo"),
    ("Brésil", ["Bresil", "Brazil"], "br"),
    ("Canada", [], "ca"),
    ("Chili", ["Chile"], "cl"),
    ("Colombie", ["Colombia"], "co"),
    ("Costa Rica", [], "cr"),
    ("Cuba", [], "cu"),
    ("Dominique", ["Dominica"], "dm"),
    ("Équateur", ["Equateur", "Ecuador"], "ec"),
    ("États-Unis", ["USA", "Etats Unis", "Etats-Unis d'Amerique"], "us"),
    ("Grenade", ["Grenada"], "gd"),
    ("Guatemala", [], "gt"),
    ("Guyana", [], "gy"),
    ("Haïti", ["Haiti"], "ht"),
    ("Honduras", [], "hn"),
    ("Jamaïque", ["Jamaique", "Jamaica"], "jm"),
    ("Mexique", ["Mexico"], "mx"),
    ("Nicaragua", [], "ni"),
    ("Panama", [], "pa"),
    ("Paraguay", [], "py"),
    ("Pérou", ["Perou", "Peru"], "pe"),
    ("République dominicaine", ["Republique dominicaine"], "do"),
    ("Saint-Christophe-et-Niévès", ["Saint Christophe et Nieves", "St Kitts"], "kn"),
    ("Sainte-Lucie", ["Sainte Lucie", "St Lucia"], "lc"),
    ("Saint-Vincent-et-les-Grenadines", ["Saint Vincent"], "vc"),
    ("Salvador", ["El Salvador"], "sv"),
    ("Suriname", [], "sr"),
    ("Trinité-et-Tobago", ["Trinite et Tobago"], "tt"),
    ("Uruguay", [], "uy"),
    ("Venezuela", [], "ve"),

    # Asie
    ("Afghanistan", [], "af"),
    ("Arabie saoudite", ["Arabie Saoudite", "Saudi Arabia"], "sa"),
    ("Arménie", ["Armenie", "Armenia"], "am"),
    ("Azerbaïdjan", ["Azerbaidjan", "Azerbaijan"], "az"),
    ("Bahreïn", ["Bahrein", "Bahrain"], "bh"),
    ("Bangladesh", [], "bd"),
    ("Bhoutan", ["Bhutan"], "bt"),
    ("Birmanie", ["Myanmar"], "mm"),
    ("Brunei", [], "bn"),
    ("Cambodge", ["Cambodia"], "kh"),
    ("Chine", ["China"], "cn"),
    ("Chypre", ["Cyprus"], "cy"),
    ("Corée du Nord", ["Coree du Nord", "North Korea"], "kp"),
    ("Corée du Sud", ["Coree du Sud", "South Korea"], "kr"),
    ("Émirats arabes unis", ["Emirats Arabes Unis", "EAU", "UAE"], "ae"),
    ("Géorgie", ["Georgie", "Georgia"], "ge"),
    ("Inde", ["India"], "in"),
    ("Indonésie", ["Indonesie", "Indonesia"], "id"),
    ("Irak", ["Iraq"], "iq"),
    ("Iran", [], "ir"),
    ("Israël", ["Israel"], "il"),
    ("Japon", ["Japan"], "jp"),
    ("Jordanie", ["Jordan"], "jo"),
    ("Kazakhstan", [], "kz"),
    ("Kirghizistan", ["Kyrgyzstan"], "kg"),
    ("Koweït", ["Koweit", "Kuwait"], "kw"),
    ("Laos", [], "la"),
    ("Liban", ["Lebanon"], "lb"),
    ("Malaisie", ["Malaysia"], "my"),
    ("Maldives", [], "mv"),
    ("Mongolie", ["Mongolia"], "mn"),
    ("Népal", ["Nepal"], "np"),
    ("Oman", [], "om"),
    ("Ouzbékistan", ["Uzbekistan"], "uz"),
    ("Pakistan", [], "pk"),
    ("Palestine", [], "ps"),
    ("Philippines", [], "ph"),
    ("Qatar", [], "qa"),
    ("Singapour", ["Singapore"], "sg"),
    ("Sri Lanka", [], "lk"),
    ("Syrie", ["Syria"], "sy"),
    ("Tadjikistan", ["Tajikistan"], "tj"),
    ("Thaïlande", ["Thailande", "Thailand"], "th"),
    ("Timor oriental", ["Timor Leste", "East Timor"], "tl"),
    ("Turkménistan", ["Turkmenistan"], "tm"),
    ("Turquie", ["Turkey", "Turkiye"], "tr"),
    ("Viêt Nam", ["Vietnam"], "vn"),
    ("Yémen", ["Yemen"], "ye"),

    # Europe
    ("Albanie", ["Albania"], "al"),
    ("Allemagne", ["Germany"], "de"),
    ("Andorre", ["Andorra"], "ad"),
    ("Autriche", ["Austria"], "at"),
    ("Belgique", ["Belgium"], "be"),
    ("Biélorussie", ["Bielorussie", "Belarus"], "by"),
    ("Bosnie-Herzégovine", ["Bosnie"], "ba"),
    ("Bulgarie", ["Bulgaria"], "bg"),
    ("Croatie", ["Croatia"], "hr"),
    ("Danemark", ["Denmark"], "dk"),
    ("Espagne", ["Spain"], "es"),
    ("Estonie", ["Estonia"], "ee"),
    ("Finlande", ["Finland"], "fi"),
    ("France", ["Republique Francaise"], "fr"),
    ("Grèce", ["Grece", "Greece"], "gr"),
    ("Hongrie", ["Hungary"], "hu"),
    ("Irlande", ["Ireland"], "ie"),
    ("Islande", ["Iceland"], "is"),
    ("Italie", ["Italy"], "it"),
    ("Lettonie", ["Latvia"], "lv"),
    ("Liechtenstein", [], "li"),
    ("Lituanie", ["Lithuania"], "lt"),
    ("Luxembourg", [], "lu"),
    ("Macédoine du Nord", ["Macedoine du Nord"], "mk"),
    ("Malte", ["Malta"], "mt"),
    ("Moldavie", ["Moldova"], "md"),
    ("Monaco", [], "mc"),
    ("Monténégro", ["Montenegro"], "me"),
    ("Norvège", ["Norvege", "Norway"], "no"),
    ("Pays-Bas", ["Pays Bas", "Netherlands", "Hollande"], "nl"),
    ("Pologne", ["Poland"], "pl"),
    ("Portugal", [], "pt"),
    ("République tchèque", ["Tchéquie", "Tchequie", "Czechia"], "cz"),
    ("Roumanie", ["Romania"], "ro"),
    ("Royaume-Uni", ["Royaume Uni", "UK", "Angleterre"], "gb"),
    ("Russie", ["Russia"], "ru"),
    ("Saint-Marin", ["Saint Marin", "San Marino"], "sm"),
    ("Serbie", ["Serbia"], "rs"),
    ("Slovaquie", ["Slovakia"], "sk"),
    ("Slovénie", ["Slovenie", "Slovenia"], "si"),
    ("Suède", ["Suede", "Sweden"], "se"),
    ("Suisse", ["Switzerland"], "ch"),
    ("Vatican", ["Saint-Siège"], "va"),

    # Océanie
    ("Australie", ["Australia"], "au"),
    ("Fidji", ["Fiji"], "fj"),
    ("Kiribati", [], "ki"),
    ("Marshall", ["Iles Marshall"], "mh"),
    ("Micronésie", ["Micronesie"], "fm"),
    ("Nauru", [], "nr"),
    ("Nouvelle-Zélande", ["Nouvelle Zelande", "New Zealand"], "nz"),
    ("Palaos", ["Palau"], "pw"),
    ("Papouasie-Nouvelle-Guinée", ["Papouasie"], "pg"),
    ("Salomon", ["Iles Salomon"], "sb"),
    ("Samoa", [], "ws"),
    ("Tonga", [], "to"),
    ("Tuvalu", [], "tv"),
    ("Vanuatu", [], "vu"),
]

data = [
    {
        "code": code,
        "name": name,
        "aliases": aliases,
        "flag": f"assets/flags/{code}.png"
    }
    for name, aliases, code in COUNTRIES_DATA
]

with open("data/countries.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Fichier data/countries.json généré avec succès (195 pays) !")